<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[24]=array(0,1,0,'6Zeu562U');
$cfg_Cs[22]=array(0,1,0,'5Zyo57q/55WZ6KiA');
$cfg_Cs[23]=array(0,1,0,'6buE6aG1');
$cfg_Cs[21]=array(0,1,1,'5LyB5Lia6YKu5bGA');
$cfg_Cs[15]=array(0,1,1,'5Lqn5ZOB5LuL57uN');
$cfg_Cs[16]=array(0,1,1,'5bu656uZ5aWX6aSQ');
$cfg_Cs[17]=array(0,1,1,'572R5bqX5bu66K6+');
$cfg_Cs[18]=array(0,1,1,'dnBz');
$cfg_Cs[19]=array(0,1,1,'5LyB5Lia5o6o5bm/');
$cfg_Cs[11]=array(0,1,1,'5biu5Yqp5Lit5b+D');
$cfg_Cs[12]=array(0,6,1,'6Jma5ouf5Li75py6');
$cfg_Cs[20]=array(0,1,1,'5Z+f5ZCN5rOo5YaM');
$cfg_Cs[14]=array(0,17,1,'5qih54mI5bGV56S6');
?>