<?php
$z[0]=Array("global","",103,133);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",846,872);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",1671,1696);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n<li class=\"\"><a href=\"[field:typeurl/]\"[field:rel/]>[field:typename/]</a></li>\r\n",1716,1940);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[4]=Array("global","",2309,2337);
$z[4][4]['name']="cfg_memberurl";
$z[5]=Array("global","",3030,3058);
$z[5][4]['name']="cfg_memberurl";
$z[6]=Array("global","",3190,3218);
$z[6][4]['name']="cfg_memberurl";

?>